//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("NoeticTools")]
[assembly: AssemblyDescription("Tools for developers")]
[assembly: AssemblyProduct("NoeticTools")]
[assembly: AssemblyCopyright("Copyright (c) Robert Smyth, 2008")]
[assembly: AssemblyTrademark("NoeticTools")]
[assembly: ComVisible(false)]
[assembly: CLSCompliant(true)]
[assembly: Guid("5ba34754-d15f-431f-42ce-89827b1a359b")]
[assembly: AssemblyVersion("1.0.0.1")]
[assembly: AssemblyFileVersion("1.0.0.1")]


